# -*- coding: utf-8 -*-
"""SimC4task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/175_7H9hBVmNr3ASgXkuDtdndgtSdt7_p
"""

import math
import random
import matplotlib.pyplot as plt

lst = [100,1000,5000,10000] 
  
eror=[]
for m in lst:
  sum=0
  sqsum=0
  for i in range (m):
    x=random.uniform(0,2)
    func= (x**2)* math.exp(x)* math.log(x)
    sum=sum+func
    sqsum=sqsum+ (func**2)

  funcavg=sum/m
  sqfuncavg= sqsum/m

  intvalue= funcavg*(2-0)
  error=((2-0)/ math.sqrt(m))*math.sqrt(sqfuncavg-(funcavg**2))
  print("Integral value: " ,intvalue)
  print("Estimated error:" ,error)
  eror.append(error)

lst=[str(i) for i in lst]
plt.bar(lst, eror, width = 0.4, color = ['red', 'green'])
plt.xlabel("N") 
plt.ylabel("Error") 
plt.show()