# -*- coding: utf-8 -*-
"""simu1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RK6Gjal_0A1U87xhJzS_1CLzj2xCuerD
"""

a='energetic'

x=''
for i in range(len(a)):

  if(x==a[i]):
    a=list(a)
    a[i]= "$"
    a = "".join(a)
  x=a[0]

print(a)