# -*- coding: utf-8 -*-
"""simu2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10-U_AH3nik5S0_qnG0YmAGkzRz_-x-9J
"""

co=[1,2,1,3,5,3,7]
items=[]
for x in range (len(co)):
  if(co[x] not in items):
    items.append(co[x])
co=items
print("Number of unique items-",co)