# -*- coding: utf-8 -*-
"""simu3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TNiaIFcVAAG-QVkXwRBfIpO42KwU1ynW
"""

co=[1,2,1,8,10,15,28]

even=0
for i in co:
  if i%2==0:
    even=even+1
odd=len(co)-even
print("ODD Number count:", odd)
print("Even Number count:", even)


for i in co[:]:
  if i%2==0:
    co.remove(i)
print(co)