# -*- coding: utf-8 -*-
"""simu4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dqxZjCYj1O6C7gpiTY1fSkYuQTmYuQZN
"""

x=7

for i in range (0,x+1):
  if(i<=int(x/2)):
    for j in range (0,i):
      print("*", end="")
  else:
    for j in range (i,x+1):
      print("*", end="")
  print()