# -*- coding: utf-8 -*-
"""simu5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tacI7oQpl3WOUubuBSmc6Kj2KKAk-lJ8
"""

x=int(input())
y=int(input())
prime=[]
for j in range (x,y+1):
  prime.append(j)
  k=(int(j+1/2))
  for i in range (2,k):
    if((j%i)==0):
      prime.remove(j)
      break

print(prime)