# -*- coding: utf-8 -*-
"""simu7(i).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ORZ-syarZspLSjjrNXlbnERo5rQvyTno
"""

#To solve the problem, initially i have coverted the data into CSV format manually and named the file 'salesdata.csv'
#Later i have used files.upload() for reading in colab

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv(io.StringIO(uploaded['salesdata.csv'].decode('utf-8')))

z= np.asarray(df.iloc[:, 0 ])
df = df.iloc[:, 1: ]
v=list(df.columns.values)
df=np.asarray(df)
df=df.T

for x in range (len(df)):
  plt.plot(z,df[x])

plt.ylim(0,14000)  
plt.ylabel('Sales Unit')
plt.xlabel('Month No.')
plt.legend(v,loc='upper right')
  


plt.show()