# -*- coding: utf-8 -*-
"""simu7(iii).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YxBzl8WyxLXI9dOP6HD0Z0z3pMbWwl_k
"""

#To solve the problem, initially i have coverted the data into CSV format manually and named the file 'salesdata.csv'
#Later i have used files.upload() for reading in colab

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv(io.StringIO(uploaded['salesdata.csv'].decode('utf-8')))

z= np.asarray(df.iloc[:, 0 ])

df = df.iloc[:, 1: ]
v=list(df.columns.values)
df=np.asarray(df)

s=[]
for i in range (len(df)):
  sum=0
  for j in range (len(df[i])):
    sum=sum+df[i][j]
  s.append(sum)
  
plt.bar(z, s, width = 0.8, color = ['red', 'green']) 
plt.ylim(0, 25000)
plt.xlabel('Month No.') 
# naming the y-axis 
plt.ylabel('Total Sell') 

  
# function to show the plot 
plt.show()