# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J88SYYz5A7CVQGRmvj7oc2gvb39k3dUf
"""

import math
import random
import matplotlib.pyplot as plt

#size of rectangle

areatri=[]



lst = [100,1000,5000,10000] 
  
# number of elemetns as input 
for m in lst:
  hits=0
  hitx=[]
  hity=[]
  missx=[]
  missy=[]

  for i in range (m):
    x=random.uniform(0,8)
    y=random.uniform(0,4)
    if x<=4:
      if (y**2)<= 4*x:
        hits=hits+1
        hitx.append(x)
        hity.append(y)

      else:
        missx.append(x)
        missy.append(y)
    else:
      if x+y<=8:
        hits=hits+1
        hitx.append(x)
        hity.append(y)

      else:
        missx.append(x)
        missy.append(y)


  areatric=32*(hits/m)
  print(areatric)
  areatri.append(areatric)
  plt.scatter(hitx, hity, label= "Hit", color= "red",  marker= ".")
  plt.scatter(missx, missy, label= "miss", color= "Green",  marker= ".")
  plt.legend() 
  plt.show()

