# -*- coding: utf-8 -*-
"""simuas6t1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1StOpaONEAIPVmvhZE6QhggxJDatiMDR5
"""

from copy import copy, deepcopy
a=[[0, 1, 0, 0, 0],[0, 0 ,1, 0, 0],[0, 1, 1, 0, 1], [0, 1, 0, 0, 1],[0, 0, 0, 0, 0]]

t= deepcopy(a)
print("In time 0")
for x in a:
  for y in x:
    print(y, end=" ")
  print()

for x in range(1,20):
  for r in range (len(a)):
    for c in range (len(a[r])):
      count=0
      for i in range(-1,2):
        for j in range(-1,2):
          if(r+i >=0 and c+j >=0 and c+j<5 and r+i <5):
            if(i!=0 or j!=0):
              if(a[r+i][c+j])==1:
                count=count+1
      t[r][c]=count
  print("In Time:",x)
  for r in range (len(a)):
    for c in range (len(a[r])):
      if(a[r][c])==1:
        if t[r][c] < 2 or t[r][c]>3:
          a[r][c]=0
      elif a[r][c] == 0:
        if t[r][c]==3:
          a[r][c]=1 
      print(a[r][c],end = " ")
    print()
  print()