# -*- coding: utf-8 -*-
"""simuas6t2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ya6AOb2pu_k2HwM9lrQIYfSamJbwFHn3
"""

import math
import random
import matplotlib.pyplot as plt

lst = [100,1000,5000] 
  
for m in lst:
  z1=[12, 6]
  z2=[3, 5]
  z3=[2, 7]
  u=[.13578431373]
  x=[]
  for i in range(2,m+1):
    new_z1= (13*z1[i-1]+11*z1[i-2]+3)%16
    z1.append(new_z1)
    u1=new_z1/16

    new_z2=(12*(z2[i-1]**2)+13*z2[i-2])%17
    z2.append(new_z2)
    u2=new_z2/17

    new_z3= (z3[i-1]**3 +z3[i-2]**2)%15
    z3.append(new_z3)
    u3=new_z3/15

    new_u=(u1+u2+u3)%1
    u.append(new_u)
  for i in range(m):
    x.append(i) 
  plt.bar(x, u, color = ['red', 'green'])
  plt.xlabel("Iteration") 
  plt.ylabel("Random Number") 
  plt.show()

print(u)